name: AcidIsland
main: com.wasteofplastic.acidisland.ASkyBlock
version: ${version}
description: AcidIsland
author: Tastybento
depend: [Vault]
softdepend: [Herochat]
load: startup
loadbefore: [Multiverse-Core]
commands:
    ai:
        description: Main player command
        aliases: [is, island, ai]
        usage:  |
             /island help
    acid:
        description: Admin commands
        usage:  |
            /acid
    aic:
        description: Game challenges
        aliases: [c, challenge, aic, aichallenge, challenges]
        usage:  |  
            /challenge
permissions:    
  acidisland.*:
    default: false
    children:
      acidisland.island.*:
        children:
          acidisland.island.go:
            description: Allow teleporting to player island
            default: true
          acidisland.island.create:
            description: Let the player use the /island command
            default: true
          acidisland.island.info:
            description: Let the player check their island level
            default: true
          acidisland.island.topten:
            description: Let the player see the top ten list
            default: true
          acidisland.island.sethome:
            description: Let the player set their island teleport point
            default: true
          acidisland.island.challenges:
            description: Let the player use the /challenges command
            default: true
          acidisland.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          acidisland.island.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
          acidisland.island.minishop:
            description: Allows usage of the minishop
            default: true
          acidisland.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
          acidisland.island.biomes:
            description: Allows biome changing
            default: true
          acidisland.island.lock:
            description: Allows island locking
            default: false
          acidisland.island.expel:
            description: Allows expelling of visitors
            default: true
          acidisland.island.ban:
            description: Allows banning of visitors
            default: false
          acidisland.island.settings:
            description: Player can see server settings
            default: true
          acidisland.island.lang:
            description: Player can select a language
            default: true
      acidisland.team.*:
        children:
          acidisland.team.create:
            description: Let a player invite other players to join a team
            default: true
          acidisland.team.kick:
            description: Let a player kick other players
            default: true
          acidisland.team.makeleader:
            description: Let a player make another player leader of the team
            default: true
          acidisland.team.join:
            description: Let a player join another player's team
            default: true
          acidisland.team.chat:
            description: Allow player to use team chat
            default: true
      acidisland.command.*:
        description: Event commands will not be run for players with this perm
        default: false
        children:
          acidisland.command.resetexempt:
            description: Player is exempt from commands run when island resets
            default: false
          acidisland.command.leaveexempt:
            description: Player is exempt from commands run when they leave or are kicked. Note will not help if player is offline.
            default: false
          acidisland.command.newexempt:
            description: Player is exempt from commands run when starting an island
            default: false
          acidisland.command.challengeexempt:
            description: Player is exempt from commands run when a challenge is completed
            default: false
      acidisland.coop:
        description: Allows player to use the coop command
        default: false    
      acidisland.craft.*:
        children:
          acidisland.craft.enderchest:
            description: Allow crafting and use of enderchests in acidisland
            default: false
      acidisland.excludetopten:
        description: Excludes player from top ten
        default: false   
      acidisland.nohunger:
        description: Excludes player from hunger if on island
        default: false   
      acidisland.settings.*:
        children:
          acidisland.settings.allowAnvilUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowArmorStandUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBeaconAccess:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBedUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBreakBlocks:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBreeding:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBrewing:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowBucketUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowChestAccess:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowCrafting:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowCropTrample:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowDoorUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowEnchanting:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowEnderPearls:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowFurnaceUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowGateUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowHorseInvAccess:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowHorseRiding:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowHurtMobs:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowLeashUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowLeverButtonUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowMusic:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowPlaceBlocks:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowPortalUse:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowPressurePlate:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowPvP:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowNetherPvP:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowRedStone:
            description: Allow player to change this island guard setting
            default: false
          acidisland.settings.allowShearing:
            description: Allow player to change this island guard setting
            default: false
      acidisland.mod.*:
        children:
          acidisland.mod.topten:
            description: Let a moderator update the top ten list
            default: op
          acidisland.mod.info:
            description: Let a moderator see info on a player
            default: op
          acidisland.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          acidisland.mod.noburn:
            description: Gives mod immunity to acid
            default: false
          acidisland.mod.resethome:
            description: Allows setting or reseting of a player's home position
            default: op
          acidisland.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          acidisland.mod.tp:
            description: Allows teleport to an island
            default: op
          acidisland.mod.tpnether:
            description: Allows teleport to a nether island
            default: op
          acidisland.mod.bypassprotect:
            description: Allow moderator to bypass island protection
            default: op
          acidisland.mod.setbiome:
            description: Allows setting player island biomes
            default: op
          acidisland.mod.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          acidisland.mod.lock:
            description: Locks or unlocks an island
            default: op
          acidisland.mod.bypasslock:
            description: Bypasses an island lock
            default: op
          acidisland.mod.signadmin:
            description: Enables warp sign admin commands
            default: op
          acidisland.mod.spy:
            description: Spy on team chats
            default: false
          acidisland.mod.removesign:
            description: Gives ability to remove warp signs
            default: false
          acidisland.mod.team:
            description: Enables modification of teams via kick and add commands
            default: false
      acidisland.admin.*:
        children:
          acidisland.mod.clearresetall:
            description: Allow clearing of island reset limit for all players
            default: op
          acidisland.admin.reload:
            description: Reload the config.yml
            default: op
          acidisland.admin.delete:
            description: Let a player completely remove a player (including island)
            default: op
          acidisland.admin.deleteisland:
            description: Let a player completely remove the island the player is on
            default: op
          acidisland.admin.register:
            description: Let a player register the nearest island to another player.
            default: op
          acidisland.admin.unregister:
            description: Removes a player from an island without deleting the island blocks.
            default: op
          acidisland.admin.purge:
            description: Let a player purge old islands.
            default: op
          acidisland.admin.noburn:
            description: Gives admin immunity to acid
            default: false
          acidisland.admin.setspawn:
            description: Allows use of spawn tools
            default: op
          acidisland.admin.setrange:
            description: Allows setting of island protection range
            default: op
          acidisland.admin.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          acidisland.admin.settingsreset:
            description: Resets all the islands to default protection settings
            default: op
